name: base
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip:
      - groq==0.9.0
      - langchain-core==0.2.22
      - langchain-groq==0.1.6
      - pandasai
      - streamlit==1.36.0